### ISSUE TITLE
State  Verification for one-off pods 

### ISSUE THREAD

**Issue by jayunit100** [jboss-openshift/ce-arq#27]
Problem: 

Arquillian unit tests verify DC/RC health, but they do not verify pod health or state.  This is desirable since some types of tests may need to do more then just verify that a RC is running.  For example:
- a one off containerized job that queries JDG hundreds of times.
- a one off performance test which should always complete successfully.

Either of these could leverage arquillians framework if arquillian was extended to validate pod state, in the same way that it auto-validates DC/RC state.

Solution:

Add a JDK annotation type that tells arquillian to verify that a given pod has reached any one of several states (Failed, Succeeded, Running, etc...).

This is similar to the PodStateVerification framework in upstream kubernetes.

**Comment by jayunit100** [comment]
cc @rcernich @willb

**Comment by alesj** [comment]
Perhaps we could add something like this to OpenShiftHandle?
(and you could then do this kind of check per-test / in test code)

**Comment by jwendell** [comment]
@jayunit100 I believe this is more suitable for Arquillian Cube upstream project.

We have the goal to move most of ce-arq functionality to arq-cube, once they are not Cloud Enablement specific. Just like this feature you proposed.

So, I'm closing this one. Please, fill an issue on arquillian cube instead.
