### ISSUE TITLE
Support YAML for @OpenShiftResource

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-arq#49]
In addition to JSON

**Comment by jwendell** [comment]
@wdecoste created this to track your work and to avoid duplicated effort. Feel free to assign this to yourself.

**Comment by bdecoste** [comment]
Thanks. Looks like this may be more complicated than I originally thought and extend beyond ce-arq. Still researching. BTW, I'm bdecoste@gmail.com not wdecoste for all the opensource work.

**Comment by rcernich** [comment]
It might be possible to ditch json and use yaml, since json is yaml.

**Comment by bdecoste** [comment]
It's blowing up when I try to use the yaml secret for datavirt. Even when I avoid the json specific logic in ce-arq and send the stream to the kubernetes-client unmarshalling it blows up. Looks like the kubernetes-client itself supports yaml so not sure yet where the problem is

**Comment by bdecoste** [comment]
https://github.com/jboss-openshift/ce-arq/pull/50
